### ISSUE TITLE
Add a squad number history scrap

### ISSUE THREAD

**Issue by FCrSTATS** [FCrSTATS/tyrone_mings#4]
Each player has a 'squad number' under their career tab (like [](https://www.transfermarkt.co.uk/ronaldinho/rueckennummern/spieler/3373))

it would be great if someone adds a function to take a player url and return the information on the squad number page, adding the age at the start of the season for each squad number. 

output as dict or pandas would be great

**Comment by mancunian1792** [comment]
Hi, I would like to take this up. 

Have few doubts. 
1 . When i take a player url as input , can i change just modify the url directly from https://www.transfermarkt.com/tyrone-mings/profil/spieler/253677 to https://www.transfermarkt.com/tyrone-mings/rueckennummern/spieler/253677 ? . Looks like profil just changes to rueckennummern .

2. And if a player has an international career , do you want that to be included as well or just their club squad numbers ?

**Comment by FCrSTATS** [comment]
Mancuian - great

1. I normally just do this with .replace("profil","rueckennummern") so you pass the main player profile URL into the function and not have to worry about correctly the url first. 

2. Yes, I think that can be a column/value in the returning object - club or country. Might even be nice to put that as a parameter of the function so the user can choose but its set default to 'both'
